spring.application.name=ridehouse

spring.datasource.url=jdbc:postgresql://localhost:5432/ridehouse
spring.datasource.username=postgres
spring.datasource.password=Marquebr

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true